# Seção 10.05 - Redes Neurais Artificiais (base censo usando keras e tensorflow)
Para esta seção, usarei a base de dados "census.csv" disponibilizada no curso do Professor Jones na UDEMY.

In [1]:
# Instruções basiconas de sempre.

# Lidar com dataframes.
import numpy as np
import pandas as pd

# Lidar com gráficos.
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
from bokeh.plotting import figure
from bokeh.io import show, output_notebook
from plotting import (multiple_histograms_plot,
                      bar_plot_with_categorical,
                      plot_confusion_matrix,
                      plot_confusion_matrix_2,
                      plot_roc)

# Lidar com preparação de dados.
from data_prep import data_prep as dp # Eu que fiz esse modulinho ("uuuuuuuuuma bosts!").
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import (train_test_split
                                     , cross_val_score
                                     , StratifiedKFold)

# Lidar com validação de modelos.
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

pd.set_option('display.max_columns', None)  
pd.set_option('display.max_colwidth', -1)
pd.set_option('display.max_rows', 500)

!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

In [2]:
nomeDaBase = "../bases/census.csv"
df = pd.read_csv(nomeDaBase, sep=",", encoding="utf-8")

In [3]:
df.head().T

,0,1,2,3,4
age,39,50,38,53,28
workclass,State-gov,Self-emp-not-inc,Private,Private,Private
final-weight,77516,83311,215646,234721,338409
education,Bachelors,Bachelors,HS-grad,11th,Bachelors
education-num,13,13,9,7,13
marital-status,Never-married,Married-civ-spouse,Divorced,Married-civ-spouse,Married-civ-spouse
occupation,Adm-clerical,Exec-managerial,Handlers-cleaners,Handlers-cleaners,Prof-specialty
relationship,Not-in-family,Husband,Not-in-family,Husband,Wife
race,White,White,White,Black,Black
sex,Male,Male,Male,Male,Female
capital-gain,2174,0,0,0,0
capital-loos,0,0,0,0,0
hour-per-week,40,13,40,40,40
native-country,United-States,United-States,United-States,United-States,Cuba
income,<=50K,<=50K,<=50K,<=50K,<=50K

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
final-weight      32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loos      32561 non-null int64
hour-per-week     32561 non-null int64
native-country    32561 non-null object
income            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,32561.0,38.581647,13.640433,17.0,28.0,37.0,48.0,90.0
final-weight,32561.0,189778.366512,105549.977697,12285.0,117827.0,178356.0,237051.0,1484705.0
education-num,32561.0,10.080679,2.572720,1.0,9.0,10.0,12.0,16.0
capital-gain,32561.0,1077.648844,7385.292085,0.0,0.0,0.0,0.0,99999.0
capital-loos,32561.0,87.303830,402.960219,0.0,0.0,0.0,0.0,4356.0
hour-per-week,32561.0,40.437456,12.347429,1.0,40.0,40.0,45.0,99.0

In [6]:
dp.cardinalidade(df)

,Atributo,Cardinalidade,Valores
6,sex,2,"[ Male, Female]"
8,income,2,"[ <=50K, >50K]"
5,race,5,"[ White, Black, Asian-Pac-Islander, Amer-Indian-Eskimo, Other]"
4,relationship,6,"[ Not-in-family, Husband, Wife, Own-child, Unmarried, Other-relative]"
2,marital-status,7,"[ Never-married, Married-civ-spouse, Divorced, Married-spouse-absent, Separated, Married-AF-spouse, Widowed]"
0,workclass,9,"[ State-gov, Self-emp-not-inc, Private, Federal-gov, Local-gov, ?, Self-emp-inc, Without-pay, Never-worked]"
3,occupation,15,"[ Adm-clerical, Exec-managerial, Handlers-cleaners, Prof-specialty, Other-service, Sales, Craft-repair, Transport-moving, Farming-fishing, Machine-op-inspct, Tech-support, ?, Protective-serv, Armed-Forces, Priv-house-serv]"
1,education,16,"[ Bachelors, HS-grad, 11th, Masters, 9th, Some-college, Assoc-acdm, Assoc-voc, 7th-8th, Doctorate, Prof-school, 5th-6th, 10th, 1st-4th, Preschool, 12th]"
7,native-country,42,"[ United-States, Cuba, Jamaica, India, ?, Mexico, South, Puerto-Rico, Honduras, England, Canada, Germany, Iran, Philippines, Italy, Poland, Columbia, Cambodia, Thailand, Ecuador, Laos, Taiwan, Haiti, Portugal, Dominican-Republic, El-Salvador, France, Guatemala, China, Japan, Yugoslavia, Peru, Outlying-US(Guam-USVI-etc), Scotland, Trinadad&Tobago, Greece, Nicaragua, Vietnam, Hong, Ireland, Hungary, Holand-Netherlands]"

### Problemas encontrados na base:

Não foram encontrados problemas na base. Não há valores nulos e nenhum valor incoerente.
**Um ponto de atenção é o valor "?" nos atributos "workclass", "occupation" e "native-country".**

#### OBSERVAÇÃO:

No mundo real, os problemas com as bases são muito piores. Deve-se ter muita atenção pois os dados podem não representar a realidade do processo.

## 1) Tratando o df para ser consumido pelo modelo

In [7]:
# Copiando df original para um novo df (df_tratado).

df_tratado = df.copy()

df_obj = df_tratado.select_dtypes(exclude=["int64", "float64"])

df_tratado[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())

for i in ["workclass", "occupation", "native-country"]:
    df_tratado[i].replace('?', np.nan, inplace=True)

state_dummies = pd.get_dummies(df_tratado[df_obj.columns], drop_first=True)

df_tratado.drop(df_obj.columns, axis=1, inplace=True)

df_tratado = pd.concat([df_tratado, state_dummies], axis=1)

In [8]:
df_tratado.head().T

,0,1,2,3,4
age,39,50,38,53,28
final-weight,77516,83311,215646,234721,338409
education-num,13,13,9,7,13
capital-gain,2174,0,0,0,0
capital-loos,0,0,0,0,0
hour-per-week,40,13,40,40,40
workclass_Local-gov,0,0,0,0,0
workclass_Never-worked,0,0,0,0,0
workclass_Private,0,0,1,1,1
workclass_Self-emp-inc,0,0,0,0,0
workclass_Self-emp-not-inc,0,1,0,0,0
workclass_State-gov,1,0,0,0,0
workclass_Without-pay,0,0,0,0,0
education_11th,0,0,0,1,0
education_12th,0,0,0,0,0
education_1st-4th,0,0,0,0,0
education_5th-6th,0,0,0,0,0
education_7th-8th,0,0,0,0,0
education_9th,0,0,0,0,0
education_Assoc-acdm,0,0,0,0,0
education_Assoc-voc,0,0,0,0,0
education_Bachelors,1,1,0,0,1
education_Doctorate,0,0,0,0,0
education_HS-grad,0,0,1,0,0
education_Masters,0,0,0,0,0
education_Preschool,0,0,0,0,0
education_Prof-school,0,0,0,0,0
education_Some-college,0,0,0,0,0
marital-status_Married-AF-spouse,0,0,0,0,0
marital-status_Married-civ-spouse,0,1,0,1,1
marital-status_Married-spouse-absent,0,0,0,0,0
marital-status_Never-married,1,0,0,0,0
marital-status_Separated,0,0,0,0,0
marital-status_Widowed,0,0,0,0,0
occupation_Armed-Forces,0,0,0,0,0
occupation_Craft-repair,0,0,0,0,0
occupation_Exec-managerial,0,1,0,0,0
occupation_Farming-fishing,0,0,0,0,0
occupation_Handlers-cleaners,0,0,1,1,0
occupation_Machine-op-inspct,0,0,0,0,0
occupation_Other-service,0,0,0,0,0
occupation_Priv-house-serv,0,0,0,0,0
occupation_Prof-specialty,0,0,0,0,1
occupation_Protective-serv,0,0,0,0,0
occupation_Sales,0,0,0,0,0
occupation_Tech-support,0,0,0,0,0
occupation_Transport-moving,0,0,0,0,0
relationship_Not-in-family,1,0,1,0,0
relationship_Other-relative,0,0,0,0,0
relationship_Own-child,0,0,0,0,0
relationship_Unmarried,0,0,0,0,0
relationship_Wife,0,0,0,0,1
race_Asian-Pac-Islander,0,0,0,0,0
race_Black,0,0,0,1,1
race_Other,0,0,0,0,0
race_White,1,1,1,0,0
sex_Male,1,1,1,1,0
native-country_Canada,0,0,0,0,0
native-country_China,0,0,0,0,0
native-country_Columbia,0,0,0,0,0
native-country_Cuba,0,0,0,0,1
native-country_Dominican-Republic,0,0,0,0,0
native-country_Ecuador,0,0,0,0,0
native-country_El-Salvador,0,0,0,0,0
native-country_England,0,0,0,0,0
native-country_France,0,0,0,0,0
native-country_Germany,0,0,0,0,0
native-country_Greece,0,0,0,0,0
native-country_Guatemala,0,0,0,0,0
native-country_Haiti,0,0,0,0,0
native-country_Holand-Netherlands,0,0,0,0,0
native-country_Honduras,0,0,0,0,0
native-country_Hong,0,0,0,0,0
native-country_Hungary,0,0,0,0,0
native-country_India,0,0,0,0,0
native-country_Iran,0,0,0,0,0
native-country_Ireland,0,0,0,0,0
native-country_Italy,0,0,0,0,0
native-country_Jamaica,0,0,0,0,0
native-country_Japan,0,0,0,0,0
native-country_Laos,0,0,0,0,0
native-country_Mexico,0,0,0,0,0
native-country_Nicaragua,0,0,0,0,0
native-country_Outlying-US(Guam-USVI-etc),0,0,0,0,0
native-country_Peru,0,0,0,0,0
native-country_Philippines,0,0,0,0,0
native-country_Poland,0,0,0,0,0
native-country_Portugal,0,0,0,0,0
native-country_Puerto-Rico,0,0,0,0,0
native-country_Scotland,0,0,0,0,0
native-country_South,0,0,0,0,0
native-country_Taiwan,0,0,0,0,0
native-country_Thailand,0,0,0,0,0
native-country_Trinadad&Tobago,0,0,0,0,0
native-country_United-States,1,1,1,1,0
native-country_Vietnam,0,0,0,0,0
native-country_Yugoslavia,0,0,0,0,0
income_>50K,0,0,0,0,0

## 2) Aplicação do modelo

### 2.1) Usando *train_test_split*

In [9]:
# Separando os fatores/previsores da resposta/target:
    
x = df_tratado.iloc[:, 0:-1]
y = df_tratado.iloc[:, -1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Escalonamento
Nesse algoritmo é importante executar o escalonamento.

In [10]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning:

Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning:

Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DataConversionWarning:

Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.

## Aplicando o modelo

In [11]:
x_train.shape

(26048, 97)

In [12]:
import keras
from keras.models import Sequential
from keras.layers import Dense

classificador = Sequential()

classificador.add(Dense(units=55, activation="relu", input_dim=97)) # camada de entrada
classificador.add(Dense(units=55, activation="relu")) # camada oculta
classificador.add(Dense(units=1, activation="sigmoid")) # camada de saída

classificador.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

classificador.fit(x_train, y_train, batch_size=10, epochs=100)

y_pred = classificador.predict(x_test)
y_pred = np.where(y_pred > .6, 1, 0)

Using TensorFlow backend.

Epoch 1/100
26048/26048 [==============================] - 5s 174us/step - loss: 0.3431 - accuracy: 0.8415
Epoch 2/100
26048/26048 [==============================] - 4s 153us/step - loss: 0.3130 - accuracy: 0.8538
Epoch 3/100
26048/26048 [==============================] - 4s 149us/step - loss: 0.3066 - accuracy: 0.8589
Epoch 4/100
26048/26048 [==============================] - 4s 154us/step - loss: 0.3015 - accuracy: 0.8617
Epoch 5/100
26048/26048 [==============================] - 4s 152us/step - loss: 0.2970 - accuracy: 0.8634
Epoch 6/100
26048/26048 [==============================] - 4s 166us/step - loss: 0.2935 - accuracy: 0.8650
Epoch 7/100
26048/26048 [==============================] - 4s 160us/step - loss: 0.2899 - accuracy: 0.8654
Epoch 8/100
26048/26048 [==============================] - 4s 157us/step - loss: 0.2851 - accuracy: 0.8691
Epoch 9/100
26048/26048 [==============================] - 4s 158us/step - loss: 0.2813 - accuracy: 0.8693
Epoch 10/100
26048/26048 [==============================] - 4s 163us/step - loss: 0.2778 - accuracy: 0.8698
Epoch 11/100
26048/26048 [==============================] - 4s 163us/step - loss: 0.2739 - accuracy: 0.8744
Epoch 12/100
26048/26048 [==============================] - 4s 152us/step - loss: 0.2708 - accuracy: 0.8752
Epoch 13/100
26048/26048 [==============================] - 4s 152us/step - loss: 0.2676 - accuracy: 0.8762
Epoch 14/100
26048/26048 [==============================] - 5s 192us/step - loss: 0.2644 - accuracy: 0.8767
Epoch 15/100
26048/26048 [==============================] - 5s 176us/step - loss: 0.2610 - accuracy: 0.8782
Epoch 16/100
26048/26048 [==============================] - 4s 152us/step - loss: 0.2566 - accuracy: 0.8794
Epoch 17/100
26048/26048 [==============================] - 4s 154us/step - loss: 0.2545 - accuracy: 0.8818
Epoch 18/100
26048/26048 [==============================] - 4s 161us/step - loss: 0.2527 - accuracy: 0.8807
Epoch 19/100
26048/26048 [==============================] - 4s 155us/step - loss: 0.2476 - accuracy: 0.8847
Epoch 20/100
26048/26048 [==============================] - 4s 156us/step - loss: 0.2467 - accuracy: 0.8853
Epoch 21/100
26048/26048 [==============================] - 4s 160us/step - loss: 0.2437 - accuracy: 0.8869
Epoch 22/100
26048/26048 [==============================] - 4s 163us/step - loss: 0.2416 - accuracy: 0.8880
Epoch 23/100
26048/26048 [==============================] - 4s 154us/step - loss: 0.2383 - accuracy: 0.8881
Epoch 24/100
26048/26048 [==============================] - 4s 158us/step - loss: 0.2360 - accuracy: 0.8902
Epoch 25/100
26048/26048 [==============================] - 4s 154us/step - loss: 0.2340 - accuracy: 0.8908
Epoch 26/100
26048/26048 [==============================] - 4s 155us/step - loss: 0.2320 - accuracy: 0.8900
Epoch 27/100
26048/26048 [==============================] - 4s 166us/step - loss: 0.2295 - accuracy: 0.8930
Epoch 28/100
26048/26048 [==============================] - 4s 155us/step - loss: 0.2277 - accuracy: 0.8940
Epoch 29/100
26048/26048 [==============================] - 4s 168us/step - loss: 0.2260 - accuracy: 0.8943
Epoch 30/100
26048/26048 [==============================] - 4s 161us/step - loss: 0.2234 - accuracy: 0.8939
Epoch 31/100
26048/26048 [==============================] - 4s 164us/step - loss: 0.2226 - accuracy: 0.8962
Epoch 32/100
26048/26048 [==============================] - 4s 160us/step - loss: 0.2192 - accuracy: 0.8966
Epoch 33/100
26048/26048 [==============================] - 5s 179us/step - loss: 0.2185 - accuracy: 0.8979
Epoch 34/100
26048/26048 [==============================] - 4s 170us/step - loss: 0.2147 - accuracy: 0.8993
Epoch 35/100
26048/26048 [==============================] - 4s 149us/step - loss: 0.2134 - accuracy: 0.8994
Epoch 36/100
26048/26048 [==============================] - 4s 158us/step - loss: 0.2130 - accuracy: 0.9001
Epoch 37/100
26048/26048 [==============================] - 5s 192us/step - loss: 0.2108 - accuracy: 0.9018
Epoch 38/100
26048/26048 [==============================] - 6s 230us/step - loss: 0.2088 - accuracy: 0.9013
Epoch 39/100
26048/26048 [==============================] - 7s 283us/step - loss: 0.2073 - accuracy: 0.9025
Epoch 40/100
26048/26048 [==============================] - 7s 273us/step - loss: 0.2064 - accuracy: 0.9036
Epoch 41/100
26048/26048 [==============================] - 8s 288us/step - loss: 0.2035 - accuracy: 0.9054
Epoch 42/100
26048/26048 [==============================] - 5s 184us/step - loss: 0.2022 - accuracy: 0.9052
Epoch 43/100
26048/26048 [==============================] - 5s 183us/step - loss: 0.2011 - accuracy: 0.9066
Epoch 44/100
26048/26048 [==============================] - 5s 182us/step - loss: 0.2001 - accuracy: 0.9052
Epoch 45/100
26048/26048 [==============================] - 5s 178us/step - loss: 0.1982 - accuracy: 0.9059
Epoch 46/100
26048/26048 [==============================] - 5s 189us/step - loss: 0.1968 - accuracy: 0.9079
Epoch 47/100
26048/26048 [==============================] - 5s 184us/step - loss: 0.1957 - accuracy: 0.9066
Epoch 48/100
26048/26048 [==============================] - 5s 190us/step - loss: 0.1951 - accuracy: 0.9073
Epoch 49/100
26048/26048 [==============================] - 5s 198us/step - loss: 0.1938 - accuracy: 0.9084
Epoch 50/100
26048/26048 [==============================] - 5s 191us/step - loss: 0.1927 - accuracy: 0.9094
Epoch 51/100
26048/26048 [==============================] - 5s 189us/step - loss: 0.1911 - accuracy: 0.9104
Epoch 52/100
26048/26048 [==============================] - 5s 181us/step - loss: 0.1898 - accuracy: 0.9101
Epoch 53/100
26048/26048 [==============================] - 5s 199us/step - loss: 0.1897 - accuracy: 0.9101
Epoch 54/100
26048/26048 [==============================] - 5s 179us/step - loss: 0.1895 - accuracy: 0.9099
Epoch 55/100
26048/26048 [==============================] - 5s 183us/step - loss: 0.1884 - accuracy: 0.9110
Epoch 56/100
26048/26048 [==============================] - 5s 185us/step - loss: 0.1857 - accuracy: 0.9126
Epoch 57/100
26048/26048 [==============================] - 5s 175us/step - loss: 0.1848 - accuracy: 0.9123
Epoch 58/100
26048/26048 [==============================] - 6s 227us/step - loss: 0.1835 - accuracy: 0.9125
Epoch 59/100
26048/26048 [==============================] - 6s 227us/step - loss: 0.1833 - accuracy: 0.9142
Epoch 60/100
26048/26048 [==============================] - 6s 247us/step - loss: 0.1835 - accuracy: 0.9133
Epoch 61/100
26048/26048 [==============================] - 6s 219us/step - loss: 0.1818 - accuracy: 0.9144
Epoch 62/100
26048/26048 [==============================] - 5s 203us/step - loss: 0.1807 - accuracy: 0.9160
Epoch 63/100
26048/26048 [==============================] - 5s 193us/step - loss: 0.1788 - accuracy: 0.9147
Epoch 64/100
26048/26048 [==============================] - 5s 204us/step - loss: 0.1778 - accuracy: 0.9164
Epoch 65/100
26048/26048 [==============================] - 6s 219us/step - loss: 0.1794 - accuracy: 0.9148
Epoch 66/100
26048/26048 [==============================] - 6s 231us/step - loss: 0.1767 - accuracy: 0.9153
Epoch 67/100
26048/26048 [==============================] - 5s 189us/step - loss: 0.1753 - accuracy: 0.9165
Epoch 68/100
26048/26048 [==============================] - 4s 161us/step - loss: 0.1782 - accuracy: 0.9155
Epoch 69/100
26048/26048 [==============================] - 4s 165us/step - loss: 0.1747 - accuracy: 0.9172
Epoch 70/100
26048/26048 [==============================] - 5s 187us/step - loss: 0.1741 - accuracy: 0.9182
Epoch 71/100
26048/26048 [==============================] - 5s 192us/step - loss: 0.1713 - accuracy: 0.9198
Epoch 72/100
26048/26048 [==============================] - 5s 192us/step - loss: 0.1746 - accuracy: 0.9182
Epoch 73/100
26048/26048 [==============================] - 4s 169us/step - loss: 0.1727 - accuracy: 0.9201
Epoch 74/100
26048/26048 [==============================] - 4s 170us/step - loss: 0.1733 - accuracy: 0.9193
Epoch 75/100
26048/26048 [==============================] - 5s 197us/step - loss: 0.1700 - accuracy: 0.9190
Epoch 76/100

26048/26048 [==============================] - 4s 154us/step - loss: 0.1685 - accuracy: 0.9229
Epoch 77/100
26048/26048 [==============================] - 5s 191us/step - loss: 0.1686 - accuracy: 0.9214
Epoch 78/100
26048/26048 [==============================] - 4s 164us/step - loss: 0.1691 - accuracy: 0.9216
Epoch 79/100
26048/26048 [==============================] - 4s 169us/step - loss: 0.1673 - accuracy: 0.9215
Epoch 80/100
26048/26048 [==============================] - 4s 146us/step - loss: 0.1675 - accuracy: 0.9218
Epoch 81/100
26048/26048 [==============================] - 4s 168us/step - loss: 0.1674 - accuracy: 0.9207
Epoch 82/100
26048/26048 [==============================] - 4s 159us/step - loss: 0.1660 - accuracy: 0.9233
Epoch 83/100
26048/26048 [==============================] - 4s 148us/step - loss: 0.1680 - accuracy: 0.9210
Epoch 84/100
26048/26048 [==============================] - 4s 162us/step - loss: 0.1644 - accuracy: 0.9226
Epoch 85/100
26048/26048 [==============================] - 4s 153us/step - loss: 0.1649 - accuracy: 0.9226
Epoch 86/100
26048/26048 [==============================] - 4s 162us/step - loss: 0.1646 - accuracy: 0.9237
Epoch 87/100
26048/26048 [==============================] - 4s 157us/step - loss: 0.1634 - accuracy: 0.9228
Epoch 88/100
26048/26048 [==============================] - 4s 152us/step - loss: 0.1629 - accuracy: 0.9245
Epoch 89/100
26048/26048 [==============================] - 4s 172us/step - loss: 0.1645 - accuracy: 0.9235
Epoch 90/100
26048/26048 [==============================] - 4s 167us/step - loss: 0.1601 - accuracy: 0.9260
Epoch 91/100
26048/26048 [==============================] - 5s 180us/step - loss: 0.1613 - accuracy: 0.9262
Epoch 92/100
26048/26048 [==============================] - 4s 158us/step - loss: 0.1586 - accuracy: 0.9254
Epoch 93/100
26048/26048 [==============================] - 4s 156us/step - loss: 0.1612 - accuracy: 0.9254
Epoch 94/100
26048/26048 [==============================] - 4s 156us/step - loss: 0.1607 - accuracy: 0.9253
Epoch 95/100
26048/26048 [==============================] - 4s 165us/step - loss: 0.1601 - accuracy: 0.9252
Epoch 96/100
26048/26048 [==============================] - 5s 173us/step - loss: 0.1596 - accuracy: 0.9249
Epoch 97/100
26048/26048 [==============================] - 4s 159us/step - loss: 0.1570 - accuracy: 0.9261
Epoch 98/100
26048/26048 [==============================] - 4s 161us/step - loss: 0.1624 - accuracy: 0.9254
Epoch 99/100
26048/26048 [==============================] - 4s 162us/step - loss: 0.1571 - accuracy: 0.9271
Epoch 100/100
26048/26048 [==============================] - 4s 171us/step - loss: 0.1575 - accuracy: 0.9275

In [ ]:
y_pred = classificador.predict(x_test)

### Verificando o como o modelo se saiu

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print("Métrica 1 (Acurácia): {:.6}.".format(
    accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)))
print("Métrica 2 (Relatório de classificação):\n{}.".format(
    classification_report(y_test, y_pred)))

plot_confusion_matrix_2(y_test, y_pred, normalize=True);